### ISSUE TITLE
 java.lang.IllegalArgumentException: Could not serialize object. Serializing Collections is not supported, please use Lists instead (found in field 'passengerUids') när man försöker skapa en resa 

### ISSUE THREAD

**Issue by ziggyt** [ziggyt/DAT256#17]
Antar att det har att göra med bytet från en arraylist av passengers till en hashmap

**Comment by gimme** [comment]
Det hade att göra med att Firebase försöker göra fields av alla public getters även om de inte hör till någon variabel. Det fanns en metod "getPassengerUids" som nu ignoreras tack vare Exclude annotation.
